name: Dev
on:
  repository_dispatch:
    types: [build]

jobs:
  dev-job:
    name: Build ESM
    runs-on: [self-hosted, Linux, X64, test]
    steps:
    - name: RUN!
      run: |
        echo "ref"
        echo ${{ github.ref }}
        echo "head ref"
        echo ${{ github.head_ref }}
        echo ${{ github.event.client_payload.sha }}